@startuml
salt
{
  {+
    {^ "Register" }
    { "Username" | "[__________]" }
    { "Password" | "[__________]" }
    { "Confirm"  | "[__________]" }
    { [Create Account] }
    { "Back to Login" }
  }
}
@enduml
